### <b>Question No. 1</b>

In [4]:
import numpy as np
list_ = ['1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

Yes, there is a difference in the data type of the variables list_ and array_list. The list_ variable is a Python list containing strings, while the array_list variable is a NumPy array containing integers.

In [5]:
print("Data type of list_:", type(list_[0]))
print("Data type of array_list:", array_list.dtype)

Data type of list_: <class 'str'>
Data type of array_list: <U1


### <b>Question No. 2

In [6]:
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

print("\nData types of elements in array_list:")
for element in array_list:
    print(type(element))

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


### <b>Question No. 3

Yes, there will be a difference in the data type of the elements present in the `list_` and `array_list` variables. When you create `array_list` with `dtype=int`, the elements will be converted to integers. Here's the code to print the data types of each element in both variables:

In [7]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

print("Data types of elements in list_:")
for element in list_:
    print(type(element))

print("\nData types of elements in array_list:")
for element in array_list:
    print(type(element))

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


### <b>Question No. 4

In [8]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# (i) Shape
print("Shape of num_array:", num_array.shape)

# (ii) Size
print("Size of num_array:", num_array.size)

Shape of num_array: (2, 3)
Size of num_array: 6


### <b>Question No. 5

In [10]:
import numpy as np

# Create a numpy array of a 3x3 matrix containing zeros
zeros_array = np.zeros((3, 3))

print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### <b>Question No. 6

In [11]:
import numpy as np

# Create an identity matrix of shape (5, 5)
identity_matrix = np.eye(5)

print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
